import type { Product } from '@/types/product'

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'book-1',
    name: 'Walking in Divine Purpose',
    description: 'A transformative guide to discovering and fulfilling your God-given destiny. This book will help you understand your purpose and walk in it with confidence.',
    price: 1500,
    compareAtPrice: 1800,
    category: 'books',
    images: ['/placeholder.svg'],
    thumbnail: '/placeholder.svg',
    stock: 25,
    sku: 'BK-WDP-001',
    featured: true,
    author: 'Apostle David Owusu',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'book-2',
    name: 'The Power of Prayer',
    description: 'Learn the secrets of effective prayer and how to develop a powerful prayer life that brings results.',
    price: 1200,
    category: 'books',
    images: ['/placeholder.svg'],
    thumbnail: '/placeholder.svg',
    stock: 30,
    sku: 'BK-POP-002',
    featured: true,
    author: 'Rev. Eunice',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'apparel-1',
    name: 'GAM Ministry T-Shirt - White',
    description: 'Premium quality cotton t-shirt with the GAM Ministry logo. Comfortable fit for everyday wear.',
    price: 2000,
    category: 'apparel',
    images: ['/placeholder.svg'],
    thumbnail: '/placeholder.svg',
    stock: 50,
    sku: 'AP-TSH-WHT-001',
    featured: true,
    size: 'M',
    color: 'White',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'apparel-2',
    name: 'GAM Ministry T-Shirt - Black',
    description: 'Premium quality cotton t-shirt with the GAM Ministry logo. Comfortable fit for everyday wear.',
    price: 2000,
    category: 'apparel',
    images: ['/placeholder.svg'],
    thumbnail: '/placeholder.svg',
    stock: 45,
    sku: 'AP-TSH-BLK-001',
    featured: false,
    size: 'L',
    color: 'Black',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'accessory-1',
    name: 'GAM Ministry Cap',
    description: 'Stylish cap with embroidered GAM Ministry logo. Adjustable strap for perfect fit.',
    price: 800,
    category: 'accessories',
    images: ['/placeholder.svg'],
    thumbnail: '/placeholder.svg',
    stock: 100,
    sku: 'AC-CAP-001',
    featured: true,
    color: 'Navy Blue',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'accessory-2',
    name: 'Faith Wristband Set',
    description: 'Set of 3 rubber wristbands with inspirational messages. Perfect for daily reminders of faith.',
    price: 300,
    category: 'accessories',
    images: ['/placeholder.svg'],
    thumbnail: '/placeholder.svg',
    stock: 200,
    sku: 'AC-WRB-001',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const PRODUCT_SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL']
export const PRODUCT_COLORS = ['White', 'Black', 'Navy Blue', 'Gray', 'Red']
